import type { WeekSchedule } from "@/components/condo/area-schedule-picker";

export type AreaType = {
  key: string;
  name: string;
  emoji: string;
  description: string;
  contextSignal: string; // sinal para a IA entender o tipo
  defaultSchedule: WeekSchedule;
  defaultCapacity: number | null;
  defaultAdvanceHours: number;
  defaultChecklist: boolean;
};

const FREE_SCHEDULE: WeekSchedule = {
  seg: { from: "06:00", to: "22:00" },
  ter: { from: "06:00", to: "22:00" },
  qua: { from: "06:00", to: "22:00" },
  qui: { from: "06:00", to: "22:00" },
  sex: { from: "06:00", to: "22:00" },
  sab: { from: "06:00", to: "22:00" },
  dom: { from: "06:00", to: "22:00" },
};

const SOCIAL_SCHEDULE: WeekSchedule = {
  seg: null,
  ter: null,
  qua: null,
  qui: null,
  sex: { from: "08:00", to: "23:00" },
  sab: { from: "08:00", to: "23:00" },
  dom: { from: "08:00", to: "18:00" },
};

const STANDARD_SCHEDULE: WeekSchedule = {
  seg: { from: "08:00", to: "22:00" },
  ter: { from: "08:00", to: "22:00" },
  qua: { from: "08:00", to: "22:00" },
  qui: { from: "08:00", to: "22:00" },
  sex: { from: "08:00", to: "22:00" },
  sab: { from: "09:00", to: "20:00" },
  dom: { from: "09:00", to: "18:00" },
};

export const AREA_CATALOG: AreaType[] = [
  {
    key: "salao_festas",
    name: "Salão de Festas",
    emoji: "🎉",
    description: "Espaço para eventos e comemorações",
    contextSignal: "Reserva exclusiva por evento, um único uso por dia, limpeza envolvida, pode ter taxa, requer aprovação do síndico",
    defaultSchedule: SOCIAL_SCHEDULE,
    defaultCapacity: 80,
    defaultAdvanceHours: 48,
    defaultChecklist: true,
  },
  {
    key: "churrasqueira",
    name: "Churrasqueira",
    emoji: "🔥",
    description: "Área de churrasco e confraternização",
    contextSignal: "Reserva por slot, itens disponíveis para uso, limpeza pós-uso obrigatória, pode ter múltiplas unidades",
    defaultSchedule: SOCIAL_SCHEDULE,
    defaultCapacity: 30,
    defaultAdvanceHours: 24,
    defaultChecklist: true,
  },
  {
    key: "piscina",
    name: "Piscina",
    emoji: "🏊",
    description: "Área de lazer aquático",
    contextSignal: "Uso coletivo, sem reserva individual por padrão, horário de funcionamento restrito, limite de pessoas simultâneas, regras de segurança",
    defaultSchedule: {
      seg: { from: "08:00", to: "20:00" },
      ter: { from: "08:00", to: "20:00" },
      qua: { from: "08:00", to: "20:00" },
      qui: { from: "08:00", to: "20:00" },
      sex: { from: "08:00", to: "20:00" },
      sab: { from: "08:00", to: "20:00" },
      dom: { from: "08:00", to: "20:00" },
    },
    defaultCapacity: 20,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "academia",
    name: "Academia / Fitness",
    emoji: "💪",
    description: "Espaço de exercícios e musculação",
    contextSignal: "Uso livre dentro do horário de funcionamento, sem reserva por padrão, sem limite rígido de pessoas",
    defaultSchedule: FREE_SCHEDULE,
    defaultCapacity: null,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "quadra",
    name: "Quadra Esportiva",
    emoji: "🏸",
    description: "Quadra poliesportiva ou de tênis",
    contextSignal: "Reserva por slot de 1-2 horas, múltiplos agendamentos por dia, máximo 4 a 10 pessoas, uso esportivo",
    defaultSchedule: STANDARD_SCHEDULE,
    defaultCapacity: 10,
    defaultAdvanceHours: 2,
    defaultChecklist: false,
  },
  {
    key: "sauna",
    name: "Sauna",
    emoji: "🧖",
    description: "Sauna seca ou a vapor",
    contextSignal: "Uso coletivo, horários fixos curtos, capacidade muito pequena, pode ter alternância masculino/feminino",
    defaultSchedule: {
      seg: { from: "16:00", to: "21:00" },
      ter: { from: "16:00", to: "21:00" },
      qua: { from: "16:00", to: "21:00" },
      qui: { from: "16:00", to: "21:00" },
      sex: { from: "16:00", to: "21:00" },
      sab: { from: "10:00", to: "20:00" },
      dom: { from: "10:00", to: "18:00" },
    },
    defaultCapacity: 6,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "espaco_gourmet",
    name: "Espaço Gourmet",
    emoji: "🍽️",
    description: "Cozinha equipada para eventos",
    contextSignal: "Reserva exclusiva, cozinha completa disponível, limpeza obrigatória pós-uso, similar ao salão de festas",
    defaultSchedule: SOCIAL_SCHEDULE,
    defaultCapacity: 40,
    defaultAdvanceHours: 48,
    defaultChecklist: true,
  },
  {
    key: "home_theater",
    name: "Home Theater / Cinema",
    emoji: "🎬",
    description: "Sala de cinema privativa",
    contextSignal: "Reserva por slot, limite de pessoas, ambiente fechado, sem comida",
    defaultSchedule: STANDARD_SCHEDULE,
    defaultCapacity: 15,
    defaultAdvanceHours: 2,
    defaultChecklist: false,
  },
  {
    key: "coworking",
    name: "Coworking / Sala de Reunião",
    emoji: "💼",
    description: "Espaço de trabalho compartilhado",
    contextSignal: "Reserva por turno ou hora, uso individual ou em grupo pequeno, ambiente silencioso",
    defaultSchedule: {
      seg: { from: "07:00", to: "22:00" },
      ter: { from: "07:00", to: "22:00" },
      qua: { from: "07:00", to: "22:00" },
      qui: { from: "07:00", to: "22:00" },
      sex: { from: "07:00", to: "22:00" },
      sab: { from: "09:00", to: "18:00" },
      dom: null,
    },
    defaultCapacity: 10,
    defaultAdvanceHours: 1,
    defaultChecklist: false,
  },
  {
    key: "playground",
    name: "Playground",
    emoji: "🛝",
    description: "Área de lazer infantil",
    contextSignal: "Uso livre, sem reserva, horário de funcionamento, área infantil com supervisão de responsável",
    defaultSchedule: {
      seg: { from: "08:00", to: "18:00" },
      ter: { from: "08:00", to: "18:00" },
      qua: { from: "08:00", to: "18:00" },
      qui: { from: "08:00", to: "18:00" },
      sex: { from: "08:00", to: "18:00" },
      sab: { from: "08:00", to: "18:00" },
      dom: { from: "08:00", to: "18:00" },
    },
    defaultCapacity: null,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "espaco_pet",
    name: "Espaço Pet / Dog Park",
    emoji: "🐾",
    description: "Área exclusiva para animais",
    contextSignal: "Uso livre, sem reserva, regras de vacinação e limpeza, responsabilidade do dono",
    defaultSchedule: FREE_SCHEDULE,
    defaultCapacity: null,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "lavanderia",
    name: "Lavanderia",
    emoji: "🧺",
    description: "Lavanderia coletiva com máquinas",
    contextSignal: "Reserva de máquina por slot de horário, tempo estimado por ciclo, organização por fila",
    defaultSchedule: {
      seg: { from: "07:00", to: "22:00" },
      ter: { from: "07:00", to: "22:00" },
      qua: { from: "07:00", to: "22:00" },
      qui: { from: "07:00", to: "22:00" },
      sex: { from: "07:00", to: "22:00" },
      sab: { from: "07:00", to: "22:00" },
      dom: { from: "08:00", to: "20:00" },
    },
    defaultCapacity: 2,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "apto_hospedes",
    name: "Apartamento de Hóspedes",
    emoji: "🏨",
    description: "Unidade para hospedagem temporária",
    contextSignal: "Reserva por diária, limite de dias seguidos, documento do hóspede, aprovação obrigatória do síndico, checklist de entrega e devolução",
    defaultSchedule: FREE_SCHEDULE,
    defaultCapacity: 4,
    defaultAdvanceHours: 72,
    defaultChecklist: true,
  },
  {
    key: "rooftop",
    name: "Rooftop / Terraço",
    emoji: "🌆",
    description: "Área aberta no topo do edifício",
    contextSignal: "Reserva por slot ou uso livre dependendo da regra, espaço aberto, pode ter horário de silêncio",
    defaultSchedule: SOCIAL_SCHEDULE,
    defaultCapacity: 30,
    defaultAdvanceHours: 24,
    defaultChecklist: false,
  },
  {
    key: "yoga_pilates",
    name: "Sala de Yoga / Pilates",
    emoji: "🧘",
    description: "Espaço para práticas corporais",
    contextSignal: "Reserva por slot de aula ou turno, ambiente silencioso, pode ter instrutor ou uso livre",
    defaultSchedule: STANDARD_SCHEDULE,
    defaultCapacity: 12,
    defaultAdvanceHours: 2,
    defaultChecklist: false,
  },
  {
    key: "horta",
    name: "Horta Comunitária",
    emoji: "🌱",
    description: "Horta coletiva do condomínio",
    contextSignal: "Sem reserva formal, canteiros distribuídos por unidade ou uso coletivo, responsabilidade compartilhada",
    defaultSchedule: FREE_SCHEDULE,
    defaultCapacity: null,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "lava_jato",
    name: "Lava-Jato / Área de Lavagem",
    emoji: "🚿",
    description: "Espaço para lavagem de veículos",
    contextSignal: "Reserva por slot, tempo estimado por uso, um veículo por vez",
    defaultSchedule: {
      seg: { from: "08:00", to: "18:00" },
      ter: { from: "08:00", to: "18:00" },
      qua: { from: "08:00", to: "18:00" },
      qui: { from: "08:00", to: "18:00" },
      sex: { from: "08:00", to: "18:00" },
      sab: { from: "08:00", to: "16:00" },
      dom: null,
    },
    defaultCapacity: 1,
    defaultAdvanceHours: 1,
    defaultChecklist: false,
  },
  {
    key: "sala_jogos",
    name: "Sala de Jogos",
    emoji: "🎱",
    description: "Sinuca, pebolim, fliperama e afins",
    contextSignal: "Uso livre ou reserva por slot, entretenimento coletivo, pode ter regra de silêncio noturno",
    defaultSchedule: STANDARD_SCHEDULE,
    defaultCapacity: 15,
    defaultAdvanceHours: 0,
    defaultChecklist: false,
  },
  {
    key: "spa",
    name: "Spa",
    emoji: "💆",
    description: "Espaço de relaxamento e bem-estar",
    contextSignal: "Reserva por slot, pode ter profissional ou uso autônomo, capacidade pequena, ambiente tranquilo",
    defaultSchedule: {
      seg: { from: "10:00", to: "20:00" },
      ter: { from: "10:00", to: "20:00" },
      qua: { from: "10:00", to: "20:00" },
      qui: { from: "10:00", to: "20:00" },
      sex: { from: "10:00", to: "20:00" },
      sab: { from: "10:00", to: "20:00" },
      dom: { from: "10:00", to: "18:00" },
    },
    defaultCapacity: 4,
    defaultAdvanceHours: 24,
    defaultChecklist: false,
  },
];
