// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {

    // Hardcoded para garantir que sempre usamos o projeto correto (jqcipbecgxssbjayusci).
    // Lovable sobrescreve VITE_SUPABASE_URL na build com o projeto deles — não usar env vars aqui.
    const SUPABASE_URL = 'https://jqcipbecgxssbjayusci.supabase.co';
    const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxY2lwYmVjZ3hzc2JqYXl1c2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NjIzOTEsImV4cCI6MjA5NTAzODM5MX0.OiC94pzx9aL8STwoQSOLyqq-cxv07DM2fZ01TK6F0nY';

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    // Validate the token via a direct HTTP request to the Supabase Auth API.
    // This bypasses any Supabase JS client quirks and works regardless of
    // which client library version is in use.
    let userData: { id: string; email?: string; [key: string]: unknown };
    try {
      const authRes = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'apikey': SUPABASE_PUBLISHABLE_KEY,
        },
      });
      if (!authRes.ok) {
        const body = await authRes.text().catch(() => '');
        throw new Error(`Auth failed: ${authRes.status} at ${SUPABASE_URL} — ${body}`);
      }
      userData = await authRes.json();
      if (!userData?.id) throw new Error(`Auth failed: no user id — project: ${SUPABASE_URL}`);
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('Auth failed')) throw err;
      throw new Error(`Auth error: ${err instanceof Error ? err.message : String(err)} — url: ${SUPABASE_URL}`);
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    return next({
      context: {
        supabase,
        userId: userData.id,
        claims: userData,
      },
    });
  },
);
