// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {

    // import.meta.env.VITE_* is inlined at build time by Vite into both the client
    // and server bundles, so it is ALWAYS the same project the browser client uses.
    // This prevents a mismatch when the deployment platform (Lovable) overrides
    // runtime process.env vars with a different project than what was compiled in.
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    // Validate the token via a direct HTTP request to the Supabase Auth API.
    // This bypasses any Supabase JS client quirks and works regardless of
    // which client library version is in use.
    let userData: { id: string; email?: string; [key: string]: unknown };
    try {
      const authRes = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'apikey': SUPABASE_PUBLISHABLE_KEY,
        },
      });
      if (!authRes.ok) {
        const body = await authRes.text().catch(() => '');
        throw new Error(`Auth failed: ${authRes.status} at ${SUPABASE_URL} — ${body}`);
      }
      userData = await authRes.json();
      if (!userData?.id) throw new Error(`Auth failed: no user id — project: ${SUPABASE_URL}`);
    } catch (err) {
      if (err instanceof Error && err.message.startsWith('Auth failed')) throw err;
      throw new Error(`Auth error: ${err instanceof Error ? err.message : String(err)} — url: ${SUPABASE_URL}`);
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    return next({
      context: {
        supabase,
        userId: userData.id,
        claims: userData,
      },
    });
  },
);
