// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  // URL hardcoded — Lovable sobrescreve process.env.SUPABASE_URL com o projeto deles.
  const SUPABASE_URL = 'https://jqcipbecgxssbjayusci.supabase.co';
  // CF_SUPABASE_SERVICE_KEY é o nome customizado — o Lovable sobrescreve SUPABASE_SERVICE_ROLE_KEY
  // com a chave do projeto deles (unpaytnhbyccpimscscj), causando "Invalid API key".
  // No Lovable: Secrets → adicionar CF_SUPABASE_SERVICE_KEY = <sua service role key>
  // No .env.local: CF_SUPABASE_SERVICE_KEY=<sua service role key>
  const SUPABASE_SERVICE_ROLE_KEY =
    process.env.CF_SUPABASE_SERVICE_KEY ??
    process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error('Missing CF_SUPABASE_SERVICE_KEY environment variable.');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
